package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const scaffoldHeader = "# generated by ct — review and commit\n"

// defaultMaxSlots is the max_slots the scaffold writes, and the slot range
// the port collision pass checks against.
const defaultMaxSlots = 9

// maxCollisionBumps caps how many times the collision pass will x10 a
// var's step before giving up and leaving a "# collision" comment instead.
const maxCollisionBumps = 3

// Scaffold generates <root>/.clone-tree/config.yaml by scanning the repo
// for compose port bindings and untracked/ignored files, writes it, and
// returns its path. It does not parse or validate the result — the
// generated file routinely needs human review (base: null vars, comment-only
// files: suggestions) before it's usable, so that's left to the next Load.
// Called by Load whenever no config exists and no --config override was
// given.
func Scaffold(root string) (string, error) {
	ports, literalComments, _, err := scanComposePorts(root, defaultMaxSlots)
	if err != nil {
		return "", fmt.Errorf("scaffold: scan compose ports: %w", err)
	}
	files, err := scanGitignored(root)
	if err != nil {
		return "", fmt.Errorf("scaffold: scan gitignored files: %w", err)
	}

	yamlText := renderScaffoldYAML(filepath.Base(root), ports, literalComments, files)

	path := filepath.Join(root, ".clone-tree", "config.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("scaffold: create .clone-tree: %w", err)
	}
	if err := os.WriteFile(path, []byte(yamlText), 0o644); err != nil {
		return "", fmt.Errorf("scaffold: write config: %w", err)
	}
	return path, nil
}

// renderScaffoldYAML builds the generated config.yaml text: a review-notice
// header, the fixed M2 defaults, discovered ports (base: null + a "set me"
// comment for anything unresolved, plus one "cannot be replicated" comment
// per service with literal, non-parameterized bindings), the live
// `files: {}` value with every suggestion bucket rendered as comments
// underneath, and empty env:/hooks: placeholders. repoName is the repo
// dir's basename (filepath.Base(root)), resolved into the worktrees_dir
// literal so the generated value works as-is without requiring the
// {repo} template.
func renderScaffoldYAML(repoName string, ports []scaffoldPort, literalComments []string, files scaffoldFiles) string {
	var b strings.Builder
	b.WriteString(scaffoldHeader)
	b.WriteString("version: 1\n")
	fmt.Fprintf(&b, "worktrees_dir: ../%s-worktrees\n", repoName)
	b.WriteString("# dns_pattern: per-worktree hostname, {name} = \"{name}.myapp.localhost\". Empty → localhost\n")
	b.WriteString("dns_pattern: \"\"\n")
	fmt.Fprintf(&b, "max_slots: %d\n", defaultMaxSlots)
	b.WriteString("\n")

	renderPorts(&b, ports, literalComments)
	b.WriteString("\n")

	b.WriteString("# env: extra KEY: value lines appended to each worktree's .env, templated with {name} {slot} {dns} {repo} {projects_dir} + the port vars.\n")
	b.WriteString("# env:\n")
	b.WriteString("#   APP_NAME: \"myapp-{name}\"\n")
	b.WriteString("#   DB_DATA_DIR: \"{projects_dir}/docker_data/db_{name}\"\n")
	b.WriteString("env: {}\n")
	b.WriteString("\n")

	renderFiles(&b, files)
	b.WriteString("\n")

	b.WriteString("hooks: {}\n")
	return b.String()
}

// renderPorts writes the `ports:` block: one entry per resolved ${VAR}
// binding (each preceded by its own comment lines, e.g. "set me" or
// "collision"), plus literalComments — one "cannot be replicated" comment
// per service with a literal host-port binding, with no accompanying
// entry (clone-tree never rewrites compose YAML, so these can't be made
// slot-aware).
func renderPorts(b *strings.Builder, ports []scaffoldPort, literalComments []string) {
	if len(ports) == 0 && len(literalComments) == 0 {
		b.WriteString("ports: {}\n")
		return
	}
	b.WriteString("ports:\n")
	for _, comment := range literalComments {
		fmt.Fprintf(b, "  %s\n", comment)
	}
	for _, p := range ports {
		for _, comment := range p.Comment {
			fmt.Fprintf(b, "  %s\n", comment)
		}
		base := "null"
		if p.Base != nil {
			base = fmt.Sprintf("%d", *p.Base)
		}
		fmt.Fprintf(b, "  %s: {base: %s, step: %d}\n", p.Name, base, p.Step)
	}
}

// renderFiles keeps files: {} as the live value — every suggestion is a
// comment underneath, one block per bucket (hardlink, ide, copy — in that
// order, so hardlink dep dirs never appear after the copy bucket starts),
// humans uncomment what they want into a real files:/ide:/copy:/hardlink:
// entry themselves. ide gets its own key (not folded into copy) since IDE
// config dirs typically need per-worktree patching via a post_create hook.
func renderFiles(b *strings.Builder, files scaffoldFiles) {
	b.WriteString("files: {}\n")

	renderFilesBucket(b, "hardlink", "gitignored dependency dirs, hardlinked instead of copied", files.hardlink)
	renderFilesBucket(b, "ide", "IDE config dirs, copied verbatim (per-worktree patching → post_create hook)", files.ide)
	renderFilesBucket(b, "copy", "gitignored files present in the main checkout", files.copy)
}

// renderFilesBucket renders one commented suggestion block:
//
//	# <key>: <description>
//	# <key>:
//	#   - item
func renderFilesBucket(b *strings.Builder, key, description string, bkt bucket) {
	items := bkt.sorted()
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(b, "# %s: %s\n", key, description)
	fmt.Fprintf(b, "# %s:\n", key)
	for _, item := range items {
		fmt.Fprintf(b, "#   - %s\n", item)
	}
}
