package config

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const scaffoldHeader = "# generated by ct — review and commit\n"

// dnsScaffoldPattern is the dns_pattern the scaffold always writes: empty,
// leaving DNS/hosts management off until a human opts in. Named as a
// constant (rather than inlined at each of its two call sites) because
// renderURLs' host = {dns}-vs-localhost rule reads it too.
const dnsScaffoldPattern = ""

// defaultMaxSlots is the max_slots the scaffold writes, and the slot range
// the port collision pass checks against.
const defaultMaxSlots = 9

// maxCollisionBumps caps how many times the collision pass will x10 a
// var's step before giving up and leaving a "# collision" comment instead.
const maxCollisionBumps = 3

// Scaffold generates <root>/.clone-tree/config.yaml by scanning the repo
// for compose port bindings and untracked/ignored files, writes it, and
// returns its path. It does not parse or validate the result — the
// generated file routinely needs human review (base: null vars, comment-only
// files: suggestions) before it's usable, so that's left to the next Load.
// Called by Load whenever no config exists and no --config override was
// given.
func Scaffold(root string) (string, error) {
	baseBranch, ok := DetectBaseBranch(root)
	if !ok {
		var err error
		baseBranch, err = promptBaseBranch()
		if err != nil {
			return "", fmt.Errorf("scaffold: %w", err)
		}
	}
	ports, literalComments, _, err := scanComposePorts(root, defaultMaxSlots)
	if err != nil {
		return "", fmt.Errorf("scaffold: scan compose ports: %w", err)
	}
	files, err := scanGitignored(root)
	if err != nil {
		return "", fmt.Errorf("scaffold: scan gitignored files: %w", err)
	}

	yamlText := renderScaffoldYAML(filepath.Base(root), baseBranch, ports, literalComments, files)

	path := filepath.Join(root, ".clone-tree", "config.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("scaffold: create .clone-tree: %w", err)
	}
	if err := os.WriteFile(path, []byte(yamlText), 0o644); err != nil {
		return "", fmt.Errorf("scaffold: write config: %w", err)
	}
	return path, nil
}

// ScaffoldOrError auto-scaffolds root's .clone-tree/config.yaml and wraps
// the written path in a *ScaffoldedError. This is the one shared entry
// point every ErrNoConfig-handling command calls: `ct create` (stops the
// pipeline, surfacing the notice as a failing command) and
// `ct create-config` (the scaffold IS the command, so it unwraps and prints
// the notice on success instead).
func ScaffoldOrError(root string) error {
	written, err := Scaffold(root)
	if err != nil {
		return err
	}
	return &ScaffoldedError{Path: written}
}

// DetectBaseBranch picks the branch new worktrees are created from: the
// first of main, master that resolves to a commit in root (git's DWIM
// resolution means this also matches an origin/<name> remote-tracking ref
// when no local branch of that name exists). ok is false when neither
// resolves — callers decide what to do then (Scaffold prompts, `ct create`
// errors).
func DetectBaseBranch(root string) (string, bool) {
	for _, candidate := range []string{"main", "master"} {
		cmd := exec.Command("git", "rev-parse", "--verify", "--quiet", candidate+"^{commit}")
		cmd.Dir = root
		if err := cmd.Run(); err == nil {
			return candidate, true
		}
	}
	return "", false
}

// promptBaseBranch is Scaffold's fallback when DetectBaseBranch found
// neither main nor master: it prompts on stderr and reads one trimmed line
// from stdin; an empty answer errors.
func promptBaseBranch() (string, error) {
	_, _ = fmt.Fprint(os.Stderr, "base branch (neither main nor master found): ")
	answer, _ := bufio.NewReader(os.Stdin).ReadString('\n')
	answer = strings.TrimSpace(answer)
	if answer == "" {
		return "", errors.New("base_branch: no answer")
	}
	return answer, nil
}

// renderScaffoldYAML builds the generated config.yaml text: a review-notice
// header, the fixed M2 defaults, discovered ports (base: null + a "set me"
// comment for anything unresolved, plus one "cannot be replicated" comment
// per service with literal, non-parameterized bindings), the live
// `files: {}` value with every suggestion bucket rendered as comments
// underneath, and empty env:/hooks: placeholders. repoName is the repo
// dir's basename (filepath.Base(root)), resolved into the worktrees_dir
// literal so the generated value works as-is without requiring the
// {repo} template. baseBranch is the autodetected branch (see
// detectBaseBranch), rendered as-is.
func renderScaffoldYAML(repoName, baseBranch string, ports []scaffoldPort, literalComments []string, files scaffoldFiles) string {
	var b strings.Builder
	b.WriteString(scaffoldHeader)
	b.WriteString("version: 1\n")
	fmt.Fprintf(&b, "worktrees_dir: ../%s-worktrees\n", repoName)
	fmt.Fprintf(&b, "base_branch: %s\n", baseBranch)
	b.WriteString("# dns_pattern: per-worktree hostname, {name} = \"{name}.myapp.localhost\". Empty → localhost\n")
	fmt.Fprintf(&b, "dns_pattern: %q\n", dnsScaffoldPattern)
	fmt.Fprintf(&b, "max_slots: %d\n", defaultMaxSlots)
	b.WriteString("\n")

	renderPorts(&b, ports, literalComments)
	b.WriteString("\n")

	// urls: suggestions' host = {dns}-vs-localhost rule reads dnsScaffoldPattern
	// too, so it stays in lockstep with the dns_pattern value written above —
	// always empty at scaffold time (Scaffold only ever runs once; it never
	// re-derives urls: from a later hand-edit of dns_pattern).
	renderURLs(&b, ports, dnsScaffoldPattern)
	b.WriteString("\n")

	b.WriteString("# env: extra KEY: value lines appended to each worktree's .env, templated with {name} {slot} {dns} {repo} {projects_dir} + the port vars.\n")
	b.WriteString("# env:\n")
	b.WriteString("#   APP_NAME: \"myapp-{name}\"\n")
	b.WriteString("#   DB_DATA_DIR: \"{projects_dir}/docker_data/db_{name}\"\n")
	b.WriteString("env: {}\n")
	b.WriteString("\n")

	renderFiles(&b, files)
	b.WriteString("\n")

	b.WriteString("hooks: {}\n")
	return b.String()
}

// renderPorts writes the `ports:` block: one entry per resolved ${VAR}
// binding (each preceded by its own comment lines, e.g. "set me" or
// "collision"), plus literalComments — one "cannot be replicated" comment
// per service with a literal host-port binding, with no accompanying
// entry (clone-tree never rewrites compose YAML, so these can't be made
// slot-aware).
func renderPorts(b *strings.Builder, ports []scaffoldPort, literalComments []string) {
	if len(ports) == 0 && len(literalComments) == 0 {
		b.WriteString("ports: {}\n")
		return
	}
	b.WriteString("ports:\n")
	for _, comment := range literalComments {
		fmt.Fprintf(b, "  %s\n", comment)
	}
	for _, p := range ports {
		for _, comment := range p.Comment {
			fmt.Fprintf(b, "  %s\n", comment)
		}
		base := "null"
		if p.Base != nil {
			base = fmt.Sprintf("%d", *p.Base)
		}
		fmt.Fprintf(b, "  %s: {base: %s, step: %d}\n", p.Name, base, p.Step)
	}
}

// urlSuggestion is one commented "label: template" line renderURLs proposes
// under urls:.
type urlSuggestion struct {
	label string
	url   string
}

// renderURLs writes the `urls:` section: the live, empty {} value (same
// philosophy as files: — nothing is active until a human uncomments it),
// plus one commented suggestion per host-exposed ports: var — a literal
// (non-parameterized) binding never reaches ports in the first place (see
// resolvePorts), so it's already excluded here too. scheme is https when
// the var's owning binding targets container port 443 or 8443, else http;
// host is {dns} when dnsPattern is non-empty, else localhost; label is the
// owning compose service name, deduped with a "-2", "-3", ... suffix when a
// service owns more than one port var (e.g. a proxy exposing both
// PROXY_HTTP_PORT and PROXY_HTTPS_PORT).
func renderURLs(b *strings.Builder, ports []scaffoldPort, dnsPattern string) {
	b.WriteString("urls: {}\n")

	suggestions := urlSuggestions(ports, dnsPattern)
	if len(suggestions) == 0 {
		return
	}
	b.WriteString("# urls: label -> URL template, expanded like env: (+ every port var, {dns}), rendered by `ct hosts <name>`\n")
	b.WriteString("# urls:\n")
	for _, s := range suggestions {
		fmt.Fprintf(b, "#   %s: %q\n", s.label, s.url)
	}
}

func urlSuggestions(ports []scaffoldPort, dnsPattern string) []urlSuggestion {
	host := "localhost"
	if dnsPattern != "" {
		host = "{dns}"
	}

	var suggestions []urlSuggestion
	serviceCount := map[string]int{}
	for _, p := range ports {
		if p.Service == "" {
			continue
		}
		scheme := "http"
		if p.ContainerPort == 443 || p.ContainerPort == 8443 {
			scheme = "https"
		}
		serviceCount[p.Service]++
		label := p.Service
		if n := serviceCount[p.Service]; n > 1 {
			label = fmt.Sprintf("%s-%d", p.Service, n)
		}
		suggestions = append(suggestions, urlSuggestion{label: label, url: fmt.Sprintf("%s://%s:{%s}/", scheme, host, p.Name)})
	}
	return suggestions
}

// renderFiles keeps files: {} as the live value — every suggestion is a
// comment underneath, one block per bucket (hardlink, ide, copy — in that
// order, so hardlink dep dirs never appear after the copy bucket starts),
// humans uncomment what they want into a real files:/ide:/copy:/hardlink:
// entry themselves. ide gets its own key (not folded into copy) since IDE
// config dirs typically need per-worktree patching via a post_create hook.
func renderFiles(b *strings.Builder, files scaffoldFiles) {
	b.WriteString("files: {}\n")

	renderFilesBucket(b, "hardlink", "gitignored dependency dirs, hardlinked instead of copied", files.hardlink)
	renderFilesBucket(b, "ide", "IDE config dirs, copied verbatim (per-worktree patching → post_create hook)", files.ide)
	renderFilesBucket(b, "copy", "gitignored files present in the main checkout", files.copy)
}

// renderFilesBucket renders one commented suggestion block:
//
//	# <key>: <description>
//	# <key>:
//	#   - item
func renderFilesBucket(b *strings.Builder, key, description string, bkt bucket) {
	items := bkt.sorted()
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(b, "# %s: %s\n", key, description)
	fmt.Fprintf(b, "# %s:\n", key)
	for _, item := range items {
		fmt.Fprintf(b, "#   - %s\n", item)
	}
}
