package config

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const scaffoldHeader = "# generated by ct — review and commit\n"

const dnsScaffoldPattern = ""

const defaultMaxSlots = 9

const maxCollisionBumps = 3

func Scaffold(root string) (string, error) {
	baseBranch, ok := DetectBaseBranch(root)
	if !ok {
		var err error
		baseBranch, err = promptBaseBranch()
		if err != nil {
			return "", fmt.Errorf("scaffold: %w", err)
		}
	}
	ports, literalComments, _, err := scanComposePorts(root, defaultMaxSlots)
	if err != nil {
		return "", fmt.Errorf("scaffold: scan compose ports: %w", err)
	}
	files, err := scanGitignored(root)
	if err != nil {
		return "", fmt.Errorf("scaffold: scan gitignored files: %w", err)
	}

	yamlText := renderScaffoldYAML(baseBranch, ports, literalComments, files)

	path := filepath.Join(root, ".clone-tree", "config.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("scaffold: create .clone-tree: %w", err)
	}
	if err := os.WriteFile(path, []byte(yamlText), 0o644); err != nil {
		return "", fmt.Errorf("scaffold: write config: %w", err)
	}
	return path, nil
}

func ScaffoldOrError(root string) error {
	written, err := Scaffold(root)
	if err != nil {
		return err
	}
	return &ScaffoldedError{Path: written}
}

// DetectBaseBranch picks the first of main, master that resolves to a
// commit in root (git's DWIM resolution means this also matches an
// origin/<name> remote-tracking ref when no local branch of that name
// exists).
func DetectBaseBranch(root string) (string, bool) {
	for _, candidate := range []string{"main", "master"} {
		cmd := exec.Command("git", "rev-parse", "--verify", "--quiet", candidate+"^{commit}")
		cmd.Dir = root
		if err := cmd.Run(); err == nil {
			return candidate, true
		}
	}
	return "", false
}

func promptBaseBranch() (string, error) {
	_, _ = fmt.Fprint(os.Stderr, "base branch (neither main nor master found): ")
	answer, _ := bufio.NewReader(os.Stdin).ReadString('\n')
	answer = strings.TrimSpace(answer)
	if answer == "" {
		return "", errors.New("base_branch: no answer")
	}
	return answer, nil
}

func renderScaffoldYAML(baseBranch string, ports []scaffoldPort, literalComments []string, files scaffoldFiles) string {
	var b strings.Builder
	b.WriteString(scaffoldHeader)
	b.WriteString("version: 1\n")
	fmt.Fprintf(&b, "base_branch: %s\n", baseBranch)
	b.WriteString("# dns_pattern: per-worktree hostname, {name} = \"{name}.myapp.localhost\". Empty → localhost\n")
	fmt.Fprintf(&b, "dns_pattern: %q\n", dnsScaffoldPattern)
	fmt.Fprintf(&b, "max_slots: %d\n", defaultMaxSlots)
	b.WriteString("\n")

	renderPorts(&b, ports, literalComments)
	b.WriteString("\n")

	renderURLs(&b, ports, dnsScaffoldPattern)
	b.WriteString("\n")

	b.WriteString("# env: extra KEY: value lines appended to each worktree's .env, templated with {name} {slot} {dns} {repo} {projects_dir} + the port vars.\n")
	b.WriteString("# env:\n")
	b.WriteString("#   APP_NAME: \"myapp-{name}\"\n")
	b.WriteString("#   DB_DATA_DIR: \"{projects_dir}/docker_data/db_{name}\"\n")
	b.WriteString("env: {}\n")
	b.WriteString("\n")

	renderFiles(&b, files)
	b.WriteString("\n")

	b.WriteString("hooks: {}\n")
	return b.String()
}

func renderPorts(b *strings.Builder, ports []scaffoldPort, literalComments []string) {
	if len(ports) == 0 && len(literalComments) == 0 {
		b.WriteString("ports: {}\n")
		return
	}
	b.WriteString("ports:\n")
	for _, comment := range literalComments {
		fmt.Fprintf(b, "  %s\n", comment)
	}
	for _, p := range ports {
		for _, comment := range p.Comment {
			fmt.Fprintf(b, "  %s\n", comment)
		}
		base := "null"
		if p.Base != nil {
			base = fmt.Sprintf("%d", *p.Base)
		}
		fmt.Fprintf(b, "  %s: {base: %s, step: %d}\n", p.Name, base, p.Step)
	}
}

type urlSuggestion struct {
	label string
	url   string
}

func renderURLs(b *strings.Builder, ports []scaffoldPort, dnsPattern string) {
	b.WriteString("urls: {}\n")

	suggestions := urlSuggestions(ports, dnsPattern)
	if len(suggestions) == 0 {
		return
	}
	b.WriteString("# urls: label -> URL template, expanded like env: (+ every port var, {dns}), rendered by `ct hosts <name>`\n")
	b.WriteString("# urls:\n")
	for _, s := range suggestions {
		fmt.Fprintf(b, "#   %s: %q\n", s.label, s.url)
	}
}

func urlSuggestions(ports []scaffoldPort, dnsPattern string) []urlSuggestion {
	host := "localhost"
	if dnsPattern != "" {
		host = "{dns}"
	}

	var suggestions []urlSuggestion
	serviceCount := map[string]int{}
	for _, p := range ports {
		if p.Service == "" {
			continue
		}
		scheme := "http"
		if p.ContainerPort == 443 || p.ContainerPort == 8443 {
			scheme = "https"
		}
		serviceCount[p.Service]++
		label := p.Service
		if n := serviceCount[p.Service]; n > 1 {
			label = fmt.Sprintf("%s-%d", p.Service, n)
		}
		suggestions = append(suggestions, urlSuggestion{label: label, url: fmt.Sprintf("%s://%s:{%s}/", scheme, host, p.Name)})
	}
	return suggestions
}

func renderFiles(b *strings.Builder, files scaffoldFiles) {
	b.WriteString("files: {}\n")

	renderFilesBucket(b, "hardlink", "gitignored dependency dirs, hardlinked instead of copied", files.hardlink)
	renderFilesBucket(b, "ide", "IDE config dirs, copied verbatim (per-worktree patching → post_create hook)", files.ide)
	renderFilesBucket(b, "copy", "gitignored files present in the main checkout", files.copy)
}

func renderFilesBucket(b *strings.Builder, key, description string, bkt bucket) {
	items := bkt.sorted()
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(b, "# %s: %s\n", key, description)
	fmt.Fprintf(b, "# %s:\n", key)
	for _, item := range items {
		fmt.Fprintf(b, "#   - %s\n", item)
	}
}
